server:
  port: 8099


spring:
  application:
    name: WHOAMI
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://docker_mysql:3306/eblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: docker_redis
    port: 6379
    password: 123
  resources:
    static-locations: file:/${web.upload-path},classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB

# redis



# log
logging:
  level:
    run.app: DEBUG
  path: ${user.dir}/logs

mybatis:
  mapper-locations: classpath:/mappering/*.xml

# 图片上传下载
web:
  upload-path: ${user.dir}/img


jwt:
  # 发行者
  name: WHOAMI
  # 密钥, 经过Base64加密, 可自行替换 默认WHOAMI
  base64Secret: V0hPQU1J
  #jwt中过期时间设置(ms)
  jwtExpires: 7200000


whoami:
  auto-scan: false
  auto-del: true


# 系统监控
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: prometheus




