server:
  port: 8099

spring:
  datasource:
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/eblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:${web.upload-path}

# pagehepler

# log
logging:
  level:
    run.app: DEBUG

mybatis:
  mapper-locations: classpath:/mappering/*.xml

# 图片上传下载
web:
  upload-path: ${user.dir}/avatar


jwt:
  # 发行者
  name: WHOAMI
  # 密钥, 经过Base64加密, 可自行替换 默认WHOAMI
  base64Secret: V0hPQU1J
  #jwt中过期时间设置(ms)
  jwtExpires: 7200000


whoami:
  auto-scan: false
  auto-del: true
