server:
  port: 8099
spring:
  application:
    name: WHOAMI
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/eblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
  resources:
    static-locations: file:/${web.upload-path},classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    properties.mail.smtp.port: 587
    password: aoswvsdtfcoeeabf
    host: smtp.qq.com
    username: 2301520611@qq.com
    default-encoding: UTF-8
    nickname: 逝痕枫舞
    from: 2301520611@qq.com



    #xss相关配置

    #  quartz:
    #    #相关属性配置
    #    properties:
    #      org:
    #        quartz:
    #          scheduler:
    #            instanceName: clusteredScheduler
    #            instanceId: AUTO
    #          jobStore:
    #            class: org.quartz.impl.jdbcjobstore.JobStoreTX
    #            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    #            tablePrefix: QRTZ_
    #            isClustered: true
    #            clusterCheckinInterval: 10000
    #            useProperties: false
    #          threadPool:
    #            class: org.quartz.simpl.SimpleThreadPool
    #            threadCount: 10
    #            threadPriority: 5
    #            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    #job-store-type: jdbc

# log
logging:
  level:
    run.app: DEBUG
  path: ${user.dir}/logs

mybatis:
  mapper-locations: classpath:/mappering/*.xml


# 图片上传下载
web:
  upload-path: ${user.dir}/img

# 文件服务器
fileServer: http://localhost:8099



jwt:
  # 发行者
  name: WHOAMI
  # 密钥, 经过Base64加密,去等 可自行替换 默认development
  base64Secret: ZGV2ZWxvcG1lbnQ
  #jwt中过期时间设置(s)
  jwtExpires: 7200
  # refresh过期时间(day)
  refreshExpires: 5


whoami:
  auto-scan: false
  auto-del: true


# 系统监控
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: prometheus




